# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.3
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: QB4Gsn7lJlr6nz16GNOxfW08foojP2O4ibEH6NkstjbZTHbKLlCIr0kHaSPvYDnfH2YYs/0FJ6F4Z+h4lHFY35MuX5OfDA7TuyS7k1Hqv18rQTdbvATZH6ftGZuw0xNco7jBu1OI/M8vXcxEdNFjmw7LGvRJ/WkBWOZFSEUWE1HfKQP+kR9lQBS/P+ClRgDFgslR5fPd6kPaAEph+DCn/cpTGPvdRdhNdnlfM2DKYPuaIART7mp7P3aiFtQjjzvVaz+aPrrRVBQv9RLmNSpniYIH4DPO5+XM1DKvnUupSNrwZIP23nlaAI7bWW451N2rT3gA32fgRJn9VjGeLAjHKEyE09ugwhCp3RDAH6fp6V3AYhoQLij4tBl3zMkCpKNNHxc8piDVV4QZNPDuIyxipaIMcADdMPI+97rvLwJaJ1AYMxzrAmuNCJXxjmn3rmaxZJqRN/I80a0xh6UbjvYe20A49NaFDw1McSJG9W4YCXF34yP6+tzMLNhLtx37GG6gdtClVPNQixSTEpzyMph7lLqtC8LHZxtWjeXf8jrwww1AQKkekV9v1zoFtHeqSbZt5eex0bD01xRs30tZ4tf0LuiwVTgb9FuRzIAnl7cLEmINJpoRPSRgZF1NQ1vkb0Ux1US5nhD4mZ3qGMcsiVHMz/ujau7rgXPl63F4aMa8fjY=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-openfoam
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: QB4Gsn7lJlr6nz16GNOxfW08foojP2O4ibEH6NkstjbZTHbKLlCIr0kHaSPvYDnfH2YYs/0FJ6F4Z+h4lHFY35MuX5OfDA7TuyS7k1Hqv18rQTdbvATZH6ftGZuw0xNco7jBu1OI/M8vXcxEdNFjmw7LGvRJ/WkBWOZFSEUWE1HfKQP+kR9lQBS/P+ClRgDFgslR5fPd6kPaAEph+DCn/cpTGPvdRdhNdnlfM2DKYPuaIART7mp7P3aiFtQjjzvVaz+aPrrRVBQv9RLmNSpniYIH4DPO5+XM1DKvnUupSNrwZIP23nlaAI7bWW451N2rT3gA32fgRJn9VjGeLAjHKEyE09ugwhCp3RDAH6fp6V3AYhoQLij4tBl3zMkCpKNNHxc8piDVV4QZNPDuIyxipaIMcADdMPI+97rvLwJaJ1AYMxzrAmuNCJXxjmn3rmaxZJqRN/I80a0xh6UbjvYe20A49NaFDw1McSJG9W4YCXF34yP6+tzMLNhLtx37GG6gdtClVPNQixSTEpzyMph7lLqtC8LHZxtWjeXf8jrwww1AQKkekV9v1zoFtHeqSbZt5eex0bD01xRs30tZ4tf0LuiwVTgb9FuRzIAnl7cLEmINJpoRPSRgZF1NQ1vkb0Ux1US5nhD4mZ3qGMcsiVHMz/ujau7rgXPl63F4aMa8fjY=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-openfoam
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: NS26lwoxojY6q13qnCYrE7QTtQSBEepcDTSyqSavYOqqfSYImL/MUZXKHzsTkvjAQz8rhd3HGUd+HgoKVLszzfEExJLyUN1i1/OjjyAljALk/G8AYDUmx9z83zv+xd3ygKNWSSsm73u/VXU+nk+EswGbTYYWhId+etV+i69eFAu0PzlmYeQbhhefsxPtUyUngwAkL1peUmUq7yTcHxWu5D7a5y8NNj2jHf+S0zKvPl8UORuB5nqX6j2wkaMcwqRW1MAQThyxrCL4EryysRK7k5VCXJdv8l8D0lOBPKTYqzCeILsm2QpGF6JxrukXdS3oIhpjShweOTLvM4voQyJnWYQ5JFbNl+sl4Qnu4ZHwGGj4RF2DmGluQDPvHvDah2W2SADE9yCQWS0Oio49ZwSA2KJYxDRCtlryD5Zw3bDCrcYZCS3INWIZNwZqOHtkqUaIOOUStMKc6TYGr9SzmPRtXi0bi/3O7gz3b/2Af1UCte7ibdP8EccKkub25Kw/AoMn/tf7agkrdD+nut44YUb0sZPaYkoPo30i5kj3CcWym73LrBNL9Q9W0+AZEEIWmx4lV0054Tm8U9O8H+sOSBpuj+UE0uq9kAlcfn5A6bH0G1D6m2Ku7QiSDFZmv4oJgGVs82gNjlQXw4obaCCb7FdkP5GOSYR5tI4aPQw7sUXk3Mw=
  file:
    - release/snap-plugin-collector-openfoam_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-openfoam
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
